### ISSUE TITLE
function can($capability) no working

### ISSUE THREAD

**Issue by ursoforte** [synapsestudios/kohana-acl#18]
I was working on the module (https://github.com/kevinsperrine/kohana-acl) for KO 3.1 and noticed that in "classes/model/acl/user.php" line 79

// Return whether or not they have access
return (bool) $this->has('capability', $capability); // use "capabilities"

linl: https://github.com/synapsestudios/kohana-acl/blob/dev%2F1.0.x/classes/model/acl/user.php#L78

An error occurs when you use "capability" without error when using "capabilities"

...Excuse my English

**Comment by jeremeamia** [comment]
You're right. Thanks for finding that. I'll fix in it our branch. I'll make sure to check out your work on the 3.1 version.
